/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/tensors/tensor.py:230: RuntimeWarning: invalid value encountered in multiply
  self._elem *= sc
/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/tensors/tensor.py:1548: UserWarning: gesdd SVD decomposition failed. Resorting to gesvd.
  warnings.warn("gesdd SVD decomposition failed. Resorting to gesvd.")
Traceback (most recent call last):
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/tensors/tensor.py", line 1544, in _normal_svd
    mat_left, singvals_tot, mat_right = xp.linalg.svd(
                                        ^^^^^^^^^^^^^^
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 1681, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 121, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/results/constrained/mps_ite/final.py", line 59, in <module>
    slist[ii].run(elem, delete_existing_folder=True, nthreads=1)
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/simulation_setup.py", line 524, in run
    self.run_single(elem, delete_existing_folder=delete_existing_folder)
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/simulation_setup.py", line 951, in run_single
    qtltn.tn_simulation.run_tn_simulation(self, params)
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/emulator/tn_simulation.py", line 293, in run_tn_simulation
    _ = optimize(
        ^^^^^^^^^
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/emulator/tn_simulation.py", line 655, in optimize
    upd_fun(
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/emulator/abstract_tn.py", line 1880, in timestep_single_tensor_link_expansion
    self.iso_towards(
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/emulator/mps_simulator.py", line 739, in iso_towards
    self.left_canonize(
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/emulator/mps_simulator.py", line 973, in left_canonize
    tensor, rr_mat, singvals, _ = self[ii].split_svd(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/tensors/tensor.py", line 1463, in split_svd
    mat_left, singvals_tot, mat_right = self._normal_svd(matrix)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/qtealeaves/tensors/tensor.py", line 1549, in _normal_svd
    mat_left, singvals_tot, mat_right = sp.linalg.svd(
                                        ^^^^^^^^^^^^^^
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/scipy/linalg/_decomp_svd.py", line 108, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/scipy/_lib/_util.py", line 321, in _asarray_validated
    a = toarray(a)
        ^^^^^^^^^^
  File "/g100/home/userexternal/pnaredi0/Tensor-Network-Hackathon-2024/TN_results/lib/python3.11/site-packages/numpy/lib/function_base.py", line 630, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
